theme = "kanagawa"

[editor]
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.lsp]
display-messages=true
display-inlay-hints=true

[keys.normal]
# make sure there is only one selection, select word under cursor, set search to selection, then switch to select mode
"C-d" = ["keep_primary_selection", "move_prev_word_start", "move_next_word_end", "search_selection", "select_mode"]

[keys.select]
# if already in select mode, just add new selection at next occurrence
"C-d" = ["search_selection", "extend_search_next"]
